services:
  # The Backend (Node.js Web Service)
  - type: web
    name: neko-editor-backend # This name must match the 'fromService' name below
    runtime: node
    rootDir: server
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Keep your API key secret and set it in the Render dashboard
      - key: NODE_VERSION
        value: "20" # Specify a recent Node.js version

  # The Frontend (React Static Site)
  - type: web
    name: neko-editor-client
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_HOST # This key is read by App.jsx
        fromService:
          type: web
          name: neko-editor-backend # Must match the backend service name
          property: host # Provides the hostname (e.g., neko-editor-backend)
    routes:
      # This rewrite is for client-side routing, ensuring all paths load the app
      - type: rewrite
        source: /*
        destination: /index.html
